#!/bin/bash

# docker-bakeup

CMD="$1"
shift  # 把 $1 拿掉，剩下的傳遞給真正的 script

case "$CMD" in
  backup)
    /usr/local/bin/backup.sh "$@"
    ;;
  restore)
    /usr/local/bin/restore.sh "$@"
    ;;
  *)
    echo "用法: docker-bakeup {backup|restore} [options]"
    exit 1
    ;;
esac

